# Generated by Django 2.2.1 on 2020-11-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mail',
        ),
    ]
